language: java
jdk:
  - oraclejdk8
notifications:
  email: false
script:
  - mvn test -B
  - cd cob_spec && mvn package && java -jar fitnesse.jar -c "HttpTestSuite.ResponseTestSuite?responder=suite&runTestsMatchingAnyTag=should_pass&format=text"
